### ISSUE TITLE
Add support for backslash-escaped multiline strings

### ISSUE THREAD

**Issue by NuckChorris** [jelera/vim-javascript-syntax#19]
All JS engines (as far as I know; tested in V8, SpiderMonkey, and JSC) support backslash-escaped multiline strings, but this still chokes on them.  Really hoping for support, as it's hard to edit userscripts when your inlined CSS blows everything up.

Example of syntax:

``` javascript
var things = "this is a\
really long\
multiline string";
```

**Comment by miguel9554** [comment]
backlash-escpaed multiline strings are not working. The changes referenced in the pull are not applied in the file.
