### ISSUE TITLE
Code folding cancelled when touching code

### ISSUE THREAD

**Issue by zanona** [jelera/vim-javascript-syntax#48]
Hey guys,

I am having problems with the code folding feature that apparently opens up all folded structures when editing the code. i.e: when creating a new `function` and typing the opening curly brace, all the remaining folds are then opened and I am required to re-close them with `zx`. The same happens with `if` statements when typing the closing curly brace.

As per the instructions shown on the README file, my `~/.vimrc` file contains:

    au FileType javascript call JavaScriptFold()

Here is a demo of the current behaviour:
![vim-js-folding](https://cloud.githubusercontent.com/assets/32017/5245666/92cc8d4e-7956-11e4-882d-bc26333653b1.gif)

If someone could point a workaround that it would be appreciated.
Thanks in advance

**Comment by jelera** [comment]
Adding `au FileType javascript call JavaScriptFold()` on your `.vimrc` file will enable folding by default, try removing that line from your vimrc.

**Comment by ryneeverett** [comment]
@jelera But shouldn't that line only execute when opening the file?

**Comment by jelera** [comment]
@ryneeverett yes, it calls `JavaScriptFold()`, which is a folding function, like using foldmethod with indent or syntax, it'll be called everytime the "rules" for indenting are met; which in this case would be creating a `function(){}` in JS.

Everyone has their own opinions about folding, so I'm thinking for moving this feature to a different repo.

**Comment by ryneeverett** [comment]
@jelera Thanks for the explanation, now that I know it's a vim quirk I'm finding lots of threads on it.

**Comment by ryneeverett** [comment]
To future searchers: see [FastFold](https://github.com/Konfekt/FastFold).

**Comment by zanona** [comment]
That's a great plugin @ryneeverett, thanks a lot for sharing. It works quite nicely.
