### ISSUE TITLE
multiple functions defined in an object causes indentation to go wrong after the second one

### ISSUE THREAD

**Issue by unphased** [jelera/vim-javascript-syntax#52]
```
#!/usr/bin/env node         
"use strict";               
module.exports = {          
  "a": function() {         
                            
  },                        
  "b": function() {         
                            
  },                        
                            
};                          
```

When you enter a new entry, it adds an extra indent. 

Verified that if i disable the plugin the indentation starts working normally again in this situation.

Also curious is that it requires two such functions, typing the "b" item does not cause erroneous indentation to occur. Note also the keys do not need to be in quotes to reproduce.

**Comment by jelera** [comment]
Well that is an Indentation problem. Vim separates syntax highlighting from indentation. On the README file, you can find a capable indent file.
