### ISSUE TITLE
Parenthesis color mismatch

### ISSUE THREAD

**Issue by obxhdx** [jelera/vim-javascript-syntax#57]
Note the parenthesis from `define` method and around `foo` parameter.

<img width="269" alt="screenshot 2015-07-17 15 57 35" src="https://cloud.githubusercontent.com/assets/761254/8758774/fd49523e-2c9c-11e5-8a1e-308e4a4be838.png">

Apparently it's related to the `function` keyword. See below examples:

<img width="231" alt="screenshot 2015-07-17 16 08 27" src="https://cloud.githubusercontent.com/assets/761254/8758856/6e8defee-2c9e-11e5-8741-4f1caf4d61a4.png">

**Comment by jelera** [comment]
According to my test, I didn't get those results. It looks like you have a  "Rainbow parenthesis plugin" or something like that.
