### ISSUE TITLE
Colors for function

### ISSUE THREAD

**Issue by SeanJM** [jelera/vim-javascript-syntax#69]
`javaScriptFuncKeyword` is highlighting incorrectly when the same theme is compared with `Atom` and `Sublime` packages of the same themes.

![Dracula theme](http://i.imgur.com/bLvSkml.jpg)

**Comment by jelera** [comment]
I'm not sure about SB or Atom syntax coloring engines, but in Vim, the syntax files (i.e. This one) recognizes only keywords or patterns in the text file so then, the colorscheme file (i.e. Monokai or Solarized) actually tells Vim how to color them.

You could create a new colorscheme file or fork an existing one, and emulate the same end result as in those editors. It is a relatively simple matter, and Drew Neil from Vimcasts has an amazing resource here, http://vimcasts.org/episodes/creating-colorschemes-for-vim/ .

I use this simple helper function on my `vimrc`, so I can see which words are being highlighted. Also you can refer to the Vim's documentation on syntax and color schemes `:h colorscheme` and `:h syntax`.

`nnoremap <Leader>syn :call <SID>SynStack()<CR>`

    function! <SID>SynStack()
     	if !exists("*synstack")
     		return
     	endif
     	echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
    endfunction
