### ISSUE TITLE
JavaScript syntax highlight broke by the slash. 

### ISSUE THREAD

**Issue by arlendotcn** [jelera/vim-javascript-syntax#77]
Testing code:
```javascript
var a = [
    '<div class="main">',
        'The result is:<strong>', iTotal/iParts, '</strong>.'
    '</div>'
].join('');
```
The syntax highlight broke by the `/`.

![js_issue](https://cloud.githubusercontent.com/assets/6712608/26751269/f0d52076-4867-11e7-8f96-d6712273a4ba.PNG)

**Comment by jelera** [comment]
I don't get the same syntax highlighting error.

Do you have any other JS plugins? Because it seems that there might be a plugin that is conflicting with the syntax file.

From what I can tell from the screenshot, the part `/iParts, '</` is being highlighted as a RegExp.
