### ISSUE TITLE
Syntax highlighthing breaks with `${}` string interpolation

### ISSUE THREAD

**Issue by vizcay** [jelera/vim-javascript-syntax#82]
<img width="824" alt="screenshot" src="https://user-images.githubusercontent.com/4545990/60756836-f72a2f00-9fd8-11e9-926a-e35336b412cf.png">

After a backtick string interpolation the highlighthing breaks (line 12).

Screenshot with `w0ng/vim-hybrid` colors scheme.

**Comment by jelera** [comment]
can you share the snippet? so I can test it

**Comment by jelera** [comment]
I actually tried to replicate the bug, but everything worked fine. In your case, it seems that the regex match falls apart after the closing curly bracket in `empresaId`, but  in my setup it all works as expected.

Another explanation maybe a plugin conflict, @vizcay do you have any other JavaScript plugin installed? 

A lot of people make the mistake of installing also either Yajs or pangloss (sometimes, even both at the same time).
