### ISSUE TITLE
add NaN, Infinity and constructor to reserved list

### ISSUE THREAD

**Issue by laoshaw** [jelera/vim-javascript-syntax#84]
these 3 words are not reserved in theory but it used as reserved so vim really should just highlight them.

**Comment by ljharb** [comment]
`NaN` and `Infinity` are one thing - they're globals. `constructor` is a property, and is in no way reserved or guaranteed to exist, so I'd suggest avoiding that one.

**Comment by laoshaw** [comment]
I had a typo in a deep nested class with a typo in constructor, it took me hours to debug, if constructor is highlighted I should have noticed it at typing time.

anyway I'm adding it to the reservedList in javascript.vim

**Comment by ljharb** [comment]
Tests would have caught it too.
